version: '3'
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME} 
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-volume:/data/db
    networks:
    - task1
  python:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: python
    ports:
      - "5000:5000"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME} 
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongo
    networks:
    - task1
volumes:
  mongo-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/data/mongo
networks:
  task1:
    driver: bridge
